# Generated by Django 2.0.6 on 2018-07-25 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.URLField()),
                ('describtion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FullWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_crawler.FullWebsite'),
        ),
    ]
